### ISSUE TITLE
not recognizing decimals properly

### ISSUE THREAD

**Issue by bm888** [IsaiasSantana/currency_textfield#1]
If you format the currency as USD like this

`final _controller = CurrencyTextFieldController(
      rightSymbol: "\$", decimalSymbol: ".", thousandSymbol: ",");`

then typing in 500000 will look like $5,000.00 but will still equal 500000. Any further math will be off by a factor of 100.

**Comment by IsaiasSantana** [comment]
@bm888  Check the **_controller.doubleValue** property. **doubleValue** contains the correct value, in this case 5.000.  I will add more unit tests to check more cases.
