### ISSUE TITLE
Quickly enter values

### ISSUE THREAD

**Issue by datpt11** [IsaiasSantana/currency_textfield#15]
I am having problem entering the value 30$. How to enter 30 instead of 3000

**Comment by Macacoazul01** [comment]
can you send your code, images...?

**Comment by Macacoazul01** [comment]
if i was able to understand your question, you're not entering 3000, its 30.00
Not sure if this will solve your problem, but you can set number of decimals to 0 on the controller:

`final CurrencyTextFieldController _controller = CurrencyTextFieldController(numberOfDecimals: 0)`

**Comment by datpt11** [comment]
Uploading Screen Recording 2024-05-31 at 10.07.20 AM.mov…

**Comment by datpt11** [comment]
https://github.com/IsaiasSantana/currency_textfield/assets/48908789/4809ff51-3dba-4057-8512-5f762c363ae9

**Comment by datpt11** [comment]
i want to enter integer and decimal separator instead of auto formatting

**Comment by Macacoazul01** [comment]
Added on 4.8.0.

There are still some bugs but its already avaliable for you to test.

Gonna open other issues to track these bugs, please open another if i forget anyone.

**Comment by Macacoazul01** [comment]
@datpt11 please use version 4.9.1
