### ISSUE TITLE
enableNegative  + showZeroValue

### ISSUE THREAD

**Issue by Aggie85** [IsaiasSantana/currency_textfield#22]
If both properties are true, then negative #s cannot be entered!

**Comment by Macacoazul01** [comment]
Gonna fix, tks

**Comment by Macacoazul01** [comment]
There are 2 bugs:
1-If you add the negative sign and then a zero, the value will become a 0.
2-If you add the sign and then add any other number, then clear the content -> you'll never be able to add the sign again

**Comment by Macacoazul01** [comment]
Fixed in `4.11.0`
