### ISSUE TITLE
Enable input and deletion of zero value

### ISSUE THREAD

**Issue by andrewmurphy353** [IsaiasSantana/currency_textfield#23]
When controller param showZeroValue is true, it is not possible to clear the textfield input. Also the controller does not permit zero input _at all_, for example 0.0 or 0

Ideally the controller _should not_ treat zero as a special case as it is a valid number. Likewise there is little need for showZeroValue if zero were to be treated the same as any other number. I expect this may involve some major changes, so as a workaround could the display, input and deletion of zero values be enabled when showZeroValue is true?

Many thanks

**Comment by Macacoazul01** [comment]
@andrewmurphy353 if you have any suggested implementation, please feel free to send a PR.
This is a valid error but i'm not sure when ill be able to solve it.

**Comment by andrewmurphy353** [comment]
@Macacoazul01 thanks for responding.
I've hacked around with the code and managed to clear zero input but was stumped at entering zero input beyond one character. From what I've seen in the approach used, in particular the parsing of input to double (which always returns 0 for zero, no matter the number of digits), I can't see an easy fix without major redesign and much effort. I think we will just have to leave it at that.

**Comment by Macacoazul01** [comment]
The conceitual "problem" here is that show zero value is to force 0 to be always there, so there is no sense for it to be removed

**Comment by Macacoazul01** [comment]
This was made to treat zero as a special number so im not sure on how to solve your problem.

Gonna look the package you [mentioned ](https://github.com/gtgalone/currency_text_input_formatter)

**Comment by andrewmurphy353** [comment]
No worries.
I'd have preferred this feature to be included in a controller, but alas I've had to switch to currency_text_input_formatter as it can display zero input and allows zero input to be nullified. It's not ideal but I'll have to live with it.
Thanks for your time.

**Comment by Macacoazul01** [comment]
@andrewmurphy353 fixed in 4.14.0.

Tks for pointing the problem
