### ISSUE TITLE
initial value

### ISSUE THREAD

**Issue by Macacoazul01** [IsaiasSantana/currency_textfield#9]
There's no option to initialize the mask.

Neither the .doubleValue or like a normal textController -> `TextEditingController(text: )`

**Comment by Macacoazul01** [comment]
Criada a 2
https://pub.dev/packages/currency_textfield_2

**Comment by IsaiasSantana** [comment]
Hi @Macacoazul01  :) Thanks to update this library and great that it's helpful to you!. I'm not working with flutter for a long time that I saw no need to update it.

**Comment by Macacoazul01** [comment]
@IsaiasSantana se vc quiser posso manter essa daqui, ao invés de continuar na outra (só preciso da liberação)
Se não, acho uma boa descontinuar essa e indicar ela aqui no pacote, pro povo que usa migrar pra atualizada

**Comment by IsaiasSantana** [comment]
@Macacoazul01 claro, vou te passar o acesso ao repositório.

**Comment by Macacoazul01** [comment]
aceitei
Vc sabe se tem alguma liberação a mais que eu preciso pra fazer o deploy no pub.dev?

**Comment by Macacoazul01** [comment]
@IsaiasSantana adiciona tambem o cirrus ci no repositorio pf?
não to conseguindo aqui
![image](https://user-images.githubusercontent.com/57464965/219751684-7d3a1836-71c8-461d-b21f-86e1fa2f5b24.png)

**Comment by IsaiasSantana** [comment]
> aceitei Vc sabe se tem alguma liberação a mais que eu preciso pra fazer o deploy no pub.dev?

@Macacoazul01  Só preciso do seu email  que adiciono lá como publisher

**Comment by Macacoazul01** [comment]
gian.b.bettega@gmail.com

**Comment by Macacoazul01** [comment]
@IsaiasSantana vc adicionando como publisher e colocando o CI eu ajusto aqui e publico

**Comment by IsaiasSantana** [comment]
@Macacoazul01 mandei o convite, no momento não consigo fazer a integração com o circus, uma  dúvida, uma github action para rodar os testes, não seria um pouco mais simples?

**Comment by Macacoazul01** [comment]
Tanto faz, o q vc preferir...
Eu conheço muito pouco dessa parte de testes.
Consegue adicionar aqui?

**Comment by IsaiasSantana** [comment]
A parte das actions nesse exato momento não :/. Se você não conseguir adicionar ela, eu quando tiver livre, vejo uma simples e coloco no projeto.

**Comment by Macacoazul01** [comment]
blz
subi a atualização sem mesmo.
Quando colocar só dar um toque
